---
################################################################################
# Home Assistant Configuration
################################################################################

# Nothing to see here. Move along.
homeassistant:
  packages: !include_dir_named packages


lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module