
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
automation living_room: !include_dir_list 1_automations
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml


lovelace:
  resources:
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module