---
################################################################################
# Home Assistant Configuration
################################################################################

# Nothing to see here. Move along.
# Linking Github to Home Assistant on Terminal
# https://www.youtube.com/watch?v=DXRApbuO6V4
homeassistant:
  packages: !include_dir_named packages


# lovelace:
#   resources:
#     - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
#       type: module