automation:
  ################################################################################
  - id: camera_home_eye_lights
    alias: "Motion in Living Room"
    trigger:
      - platform: device
        device_id: !secret nest_home_eye_device_id
        domain: nest
        type: camera_person
    action:
      - alias: 'State Handler'
        choose:
          - conditions:
              - alias: 'Sun is down'
                condition: state
                entity_id: sun.sun
                state: 'below_horizon'
            sequence:
              - service: notify.notify
                data:
                  message: "On - Living Room Lights."
              - service: light.turn_on
                target:
                  entity_id: light.living_room_lights
              - delay:
                  hours: 0
                  minutes: 3
                  seconds: 0
                  milliseconds: 0
              - service: notify.notify
                data:
                  message: "Off - Living Room Lights."
              - service: light.turn_off
                target:
                  entity_id: light.living_room_lights
          - conditions:
              - alias: 'Sun is up'
                condition: state
                entity_id: sun.sun
                state: 'above_horizon'
            sequence: 
              - service: notify.notify
                data:
                  message: "Activity in Living Room during the day"
    mode: single
  # - id: camera_front_yard_lights
  #   alias: "Lights on detection of motion in front yard"
  #   description: ""
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.front_yard_motion_detected
  #         - binary_sensor.front_yard_person_detected
  #       to: 
  #         - "on"
  #         - "off"
  #   action:
  #     - if:
  #         - condition: state
  #           entity_id: 
  #           - binary_sensor.front_yard_motion_detected
  #           - binary_sensor.front_yard_person_detected
  #           state: 'on'
  #       then:
  #         - service: light.turn_on
  #           target:
  #             entity_id: light.living_room_lights    
  #         - service: notify.mobile_app_pixel_6_pro
  #           data:
  #             message: "Front Yard: Motion detected (On - Living Room Lights)"
  #       else:
  #         - service: light.turn_off
  #           target:
  #             entity_id: light.living_room_lights     
  #         - service: notify.mobile_app_pixel_6_pro
  #           data:
  #             message: "Front Yard: Empty (Off - Living Room Lights)"
