---
### System Notifications ###

automation:
  ################################################################################
  - id: system_notification_update
    alias: 'System - Notification - Update Available'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.notify
      data:
        message: 'An update for Home Assistant is available.'
  ################################################################################

  ################################################################################
  - id: system_notification_new_device
    alias: 'System - Notification - New Device'
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.notify
        data_template:
          message: >
            Home Assistant has discovered a new device:
            {{trigger.event.data.entity_id}}
          title: New Device
  ################################################################################

  ################################################################################
  - id: system_notification_start
    alias: 'System - Notification - Home Assistant Start'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: notify.notify
      data:
        message: 'Home Assistant has started!'
  ################################################################################

  ################################################################################
  - id: system_notification_certification_expiration
    alias: 'System - Notification - Home Assistant Certificate'
    trigger:
      platform: template
      value_template: >
        {{ states.sensor.ssl_certificate_expiry.state | int  <= 14 }}
    condition:
      condition: template
      value_template: >
        {{ states.sensor.ssl_certificate_expiry.state != "unknown" }}
    action:
      service: notify.notify
      data_template:
        message: >
          Home Assistant's certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days.

################################################################################
  - id: Front Yard Motion Detection
    alias: Capture Image on Trigger, Send Mobile Notification with Actions, Snooze or Alarm via Actions
    description: ""
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_yard_motion_detected
          - binary_sensor.front_yard_person_detected
        to: "on"
        id: sensor
      - platform: event
        event_type: mobile_app_notification_action
        id: snooze
        event_data:
          action: SNOOZE
      - platform: event
        event_type: mobile_app_notification_action
        id: alarm
        event_data:
          action: ALARM
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: sensor
            sequence:
              - service: notify.mobile_app_pixel_6_pro
                data:
                  message: Motion detected
                  data:
                    image: /api/image_proxy/image.entrance_event_image
                    actions:
                      - action: ALARM
                        title: Alarm
                      - action: SNOOZE
                        title: Snooze
          - conditions:
              - condition: trigger
                id: snooze
            sequence:
              - service: eufy_security.snooze
                data:
                  snooze_time: 10
                  snooze_chime: false
                  snooze_motion: true
                  snooze_homebase: false
                target:
                  entity_id: camera.front_yard
          - conditions:
              - condition: trigger
                id: alarm
            sequence:
              - service: eufy_security.trigger_camera_alarm_with_duration
                data:
                  duration: 1
                target:
                  entity_id: camera.front_yard
    mode: single